// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package containerManager

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// ContainerManagerClient is the client API for ContainerManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ContainerManagerClient interface {
	DeleteContainer(ctx context.Context, in *DeleteContainerRequest, opts ...grpc.CallOption) (*DeleteContainerResponse, error)
}

type containerManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewContainerManagerClient(cc grpc.ClientConnInterface) ContainerManagerClient {
	return &containerManagerClient{cc}
}

func (c *containerManagerClient) DeleteContainer(ctx context.Context, in *DeleteContainerRequest, opts ...grpc.CallOption) (*DeleteContainerResponse, error) {
	out := new(DeleteContainerResponse)
	err := c.cc.Invoke(ctx, "/containerManager/deleteContainer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContainerManagerServer is the server API for ContainerManager service.
// All implementations must embed UnimplementedContainerManagerServer
// for forward compatibility
type ContainerManagerServer interface {
	DeleteContainer(context.Context, *DeleteContainerRequest) (*DeleteContainerResponse, error)
	mustEmbedUnimplementedContainerManagerServer()
}

// UnimplementedContainerManagerServer must be embedded to have forward compatible implementations.
type UnimplementedContainerManagerServer struct {
}

func (UnimplementedContainerManagerServer) DeleteContainer(context.Context, *DeleteContainerRequest) (*DeleteContainerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteContainer not implemented")
}
func (UnimplementedContainerManagerServer) mustEmbedUnimplementedContainerManagerServer() {}

// UnsafeContainerManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ContainerManagerServer will
// result in compilation errors.
type UnsafeContainerManagerServer interface {
	mustEmbedUnimplementedContainerManagerServer()
}

func RegisterContainerManagerServer(s grpc.ServiceRegistrar, srv ContainerManagerServer) {
	s.RegisterService(&_ContainerManager_serviceDesc, srv)
}

func _ContainerManager_DeleteContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteContainerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContainerManagerServer).DeleteContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/containerManager/deleteContainer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContainerManagerServer).DeleteContainer(ctx, req.(*DeleteContainerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ContainerManager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "containerManager",
	HandlerType: (*ContainerManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "deleteContainer",
			Handler:    _ContainerManager_DeleteContainer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "containerManager.proto",
}
