// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: containerManager.proto

package containerManager

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ContainerMeta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	XCid    string `protobuf:"bytes,1,opt,name=_cid,json=Cid,proto3" json:"_cid,omitempty"`
	XNodeId string `protobuf:"bytes,2,opt,name=_nodeId,json=NodeId,proto3" json:"_nodeId,omitempty"`
	Force   bool   `protobuf:"varint,3,opt,name=force,proto3" json:"force,omitempty"`
	Timeout int64  `protobuf:"varint,4,opt,name=timeout,proto3" json:"timeout,omitempty"`
}

func (x *ContainerMeta) Reset() {
	*x = ContainerMeta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_containerManager_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContainerMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerMeta) ProtoMessage() {}

func (x *ContainerMeta) ProtoReflect() protoreflect.Message {
	mi := &file_containerManager_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerMeta.ProtoReflect.Descriptor instead.
func (*ContainerMeta) Descriptor() ([]byte, []int) {
	return file_containerManager_proto_rawDescGZIP(), []int{0}
}

func (x *ContainerMeta) GetXCid() string {
	if x != nil {
		return x.XCid
	}
	return ""
}

func (x *ContainerMeta) GetXNodeId() string {
	if x != nil {
		return x.XNodeId
	}
	return ""
}

func (x *ContainerMeta) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

func (x *ContainerMeta) GetTimeout() int64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

type KongServiceMeta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceName string `protobuf:"bytes,1,opt,name=serviceName,proto3" json:"serviceName,omitempty"`
	Route       string `protobuf:"bytes,2,opt,name=route,proto3" json:"route,omitempty"`
	TargetPath  string `protobuf:"bytes,3,opt,name=targetPath,proto3" json:"targetPath,omitempty"`
}

func (x *KongServiceMeta) Reset() {
	*x = KongServiceMeta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_containerManager_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KongServiceMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KongServiceMeta) ProtoMessage() {}

func (x *KongServiceMeta) ProtoReflect() protoreflect.Message {
	mi := &file_containerManager_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KongServiceMeta.ProtoReflect.Descriptor instead.
func (*KongServiceMeta) Descriptor() ([]byte, []int) {
	return file_containerManager_proto_rawDescGZIP(), []int{1}
}

func (x *KongServiceMeta) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *KongServiceMeta) GetRoute() string {
	if x != nil {
		return x.Route
	}
	return ""
}

func (x *KongServiceMeta) GetTargetPath() string {
	if x != nil {
		return x.TargetPath
	}
	return ""
}

type KongUpstreamMeta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UpstreamName string `protobuf:"bytes,1,opt,name=upstreamName,proto3" json:"upstreamName,omitempty"`
	Hashon       string `protobuf:"bytes,2,opt,name=hashon,proto3" json:"hashon,omitempty"`
}

func (x *KongUpstreamMeta) Reset() {
	*x = KongUpstreamMeta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_containerManager_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KongUpstreamMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KongUpstreamMeta) ProtoMessage() {}

func (x *KongUpstreamMeta) ProtoReflect() protoreflect.Message {
	mi := &file_containerManager_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KongUpstreamMeta.ProtoReflect.Descriptor instead.
func (*KongUpstreamMeta) Descriptor() ([]byte, []int) {
	return file_containerManager_proto_rawDescGZIP(), []int{2}
}

func (x *KongUpstreamMeta) GetUpstreamName() string {
	if x != nil {
		return x.UpstreamName
	}
	return ""
}

func (x *KongUpstreamMeta) GetHashon() string {
	if x != nil {
		return x.Hashon
	}
	return ""
}

type KongMeta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KongServiceMeta  *KongServiceMeta  `protobuf:"bytes,1,opt,name=kongServiceMeta,proto3" json:"kongServiceMeta,omitempty"`
	KongUpstreamMeta *KongUpstreamMeta `protobuf:"bytes,2,opt,name=kongUpstreamMeta,proto3" json:"kongUpstreamMeta,omitempty"`
}

func (x *KongMeta) Reset() {
	*x = KongMeta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_containerManager_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KongMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KongMeta) ProtoMessage() {}

func (x *KongMeta) ProtoReflect() protoreflect.Message {
	mi := &file_containerManager_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KongMeta.ProtoReflect.Descriptor instead.
func (*KongMeta) Descriptor() ([]byte, []int) {
	return file_containerManager_proto_rawDescGZIP(), []int{3}
}

func (x *KongMeta) GetKongServiceMeta() *KongServiceMeta {
	if x != nil {
		return x.KongServiceMeta
	}
	return nil
}

func (x *KongMeta) GetKongUpstreamMeta() *KongUpstreamMeta {
	if x != nil {
		return x.KongUpstreamMeta
	}
	return nil
}

type ServiceMeta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name          string    `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	Image         string    `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	ImageUri      string    `protobuf:"bytes,2,opt,name=imageUri,proto3" json:"imageUri,omitempty"`
	ContainerPort string    `protobuf:"bytes,3,opt,name=ContainerPort,proto3" json:"ContainerPort,omitempty"`
	BasePort      string    `protobuf:"bytes,4,opt,name=BasePort,proto3" json:"BasePort,omitempty"`
	MaxPort       string    `protobuf:"bytes,5,opt,name=MaxPort,proto3" json:"MaxPort,omitempty"`
	KongMeta      *KongMeta `protobuf:"bytes,6,opt,name=kongMeta,proto3" json:"kongMeta,omitempty"`
}

func (x *ServiceMeta) Reset() {
	*x = ServiceMeta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_containerManager_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceMeta) ProtoMessage() {}

func (x *ServiceMeta) ProtoReflect() protoreflect.Message {
	mi := &file_containerManager_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceMeta.ProtoReflect.Descriptor instead.
func (*ServiceMeta) Descriptor() ([]byte, []int) {
	return file_containerManager_proto_rawDescGZIP(), []int{4}
}

func (x *ServiceMeta) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceMeta) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ServiceMeta) GetImageUri() string {
	if x != nil {
		return x.ImageUri
	}
	return ""
}

func (x *ServiceMeta) GetContainerPort() string {
	if x != nil {
		return x.ContainerPort
	}
	return ""
}

func (x *ServiceMeta) GetBasePort() string {
	if x != nil {
		return x.BasePort
	}
	return ""
}

func (x *ServiceMeta) GetMaxPort() string {
	if x != nil {
		return x.MaxPort
	}
	return ""
}

func (x *ServiceMeta) GetKongMeta() *KongMeta {
	if x != nil {
		return x.KongMeta
	}
	return nil
}

type ServiceMetaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceMeta []*ServiceMeta `protobuf:"bytes,1,rep,name=serviceMeta,proto3" json:"serviceMeta,omitempty"`
}

func (x *ServiceMetaResponse) Reset() {
	*x = ServiceMetaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_containerManager_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceMetaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceMetaResponse) ProtoMessage() {}

func (x *ServiceMetaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_containerManager_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceMetaResponse.ProtoReflect.Descriptor instead.
func (*ServiceMetaResponse) Descriptor() ([]byte, []int) {
	return file_containerManager_proto_rawDescGZIP(), []int{5}
}

func (x *ServiceMetaResponse) GetServiceMeta() []*ServiceMeta {
	if x != nil {
		return x.ServiceMeta
	}
	return nil
}

type ServiceMetaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ServiceMetaRequest) Reset() {
	*x = ServiceMetaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_containerManager_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceMetaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceMetaRequest) ProtoMessage() {}

func (x *ServiceMetaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_containerManager_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceMetaRequest.ProtoReflect.Descriptor instead.
func (*ServiceMetaRequest) Descriptor() ([]byte, []int) {
	return file_containerManager_proto_rawDescGZIP(), []int{6}
}

type DeleteContainerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Meta *ContainerMeta `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
}

func (x *DeleteContainerRequest) Reset() {
	*x = DeleteContainerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_containerManager_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteContainerRequest) ProtoMessage() {}

func (x *DeleteContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_containerManager_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteContainerRequest.ProtoReflect.Descriptor instead.
func (*DeleteContainerRequest) Descriptor() ([]byte, []int) {
	return file_containerManager_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteContainerRequest) GetMeta() *ContainerMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type DeleteContainerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *DeleteContainerResponse) Reset() {
	*x = DeleteContainerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_containerManager_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteContainerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteContainerResponse) ProtoMessage() {}

func (x *DeleteContainerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_containerManager_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteContainerResponse.ProtoReflect.Descriptor instead.
func (*DeleteContainerResponse) Descriptor() ([]byte, []int) {
	return file_containerManager_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteContainerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type FlakeMeta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ContainerId string `protobuf:"bytes,2,opt,name=containerId,proto3" json:"containerId,omitempty"`
	HostId      string `protobuf:"bytes,3,opt,name=hostId,proto3" json:"hostId,omitempty"`
	Service     string `protobuf:"bytes,4,opt,name=service,proto3" json:"service,omitempty"`
	Ip          string `protobuf:"bytes,5,opt,name=ip,proto3" json:"ip,omitempty"`
	Port        string `protobuf:"bytes,6,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *FlakeMeta) Reset() {
	*x = FlakeMeta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_containerManager_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FlakeMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlakeMeta) ProtoMessage() {}

func (x *FlakeMeta) ProtoReflect() protoreflect.Message {
	mi := &file_containerManager_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlakeMeta.ProtoReflect.Descriptor instead.
func (*FlakeMeta) Descriptor() ([]byte, []int) {
	return file_containerManager_proto_rawDescGZIP(), []int{9}
}

func (x *FlakeMeta) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FlakeMeta) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *FlakeMeta) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *FlakeMeta) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *FlakeMeta) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *FlakeMeta) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

type FlakeMetaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FlakeMeta []*FlakeMeta `protobuf:"bytes,1,rep,name=flakeMeta,proto3" json:"flakeMeta,omitempty"`
}

func (x *FlakeMetaResponse) Reset() {
	*x = FlakeMetaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_containerManager_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FlakeMetaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlakeMetaResponse) ProtoMessage() {}

func (x *FlakeMetaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_containerManager_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlakeMetaResponse.ProtoReflect.Descriptor instead.
func (*FlakeMetaResponse) Descriptor() ([]byte, []int) {
	return file_containerManager_proto_rawDescGZIP(), []int{10}
}

func (x *FlakeMetaResponse) GetFlakeMeta() []*FlakeMeta {
	if x != nil {
		return x.FlakeMeta
	}
	return nil
}

type FlakeStats struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	MemUsage string `protobuf:"bytes,1,opt,name=memUsage,proto3" json:"memUsage,omitempty"`
	CpuPer   string `protobuf:"bytes,2,opt,name=cpuPer,proto3" json:"cpuPer,omitempty"`
	Network  string `protobuf:"bytes,3,opt,name=Network,proto3" json:"Network,omitempty"`
}

func (x *FlakeStats) Reset() {
	*x = FlakeStats{}
	if protoimpl.UnsafeEnabled {
		mi := &file_containerManager_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FlakeStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlakeStats) ProtoMessage() {}

func (x *FlakeStats) ProtoReflect() protoreflect.Message {
	mi := &file_containerManager_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlakeStats.ProtoReflect.Descriptor instead.
func (*FlakeStats) Descriptor() ([]byte, []int) {
	return file_containerManager_proto_rawDescGZIP(), []int{11}
}

func (x *FlakeStats) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FlakeStats) GetMemUsage() string {
	if x != nil {
		return x.MemUsage
	}
	return ""
}

func (x *FlakeStats) GetCpuPer() string {
	if x != nil {
		return x.CpuPer
	}
	return ""
}

func (x *FlakeStats) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

type FlakeStatsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FlakeStats []*FlakeStats `protobuf:"bytes,1,rep,name=flakeStats,proto3" json:"flakeStats,omitempty"`
}

func (x *FlakeStatsResponse) Reset() {
	*x = FlakeStatsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_containerManager_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FlakeStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlakeStatsResponse) ProtoMessage() {}

func (x *FlakeStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_containerManager_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlakeStatsResponse.ProtoReflect.Descriptor instead.
func (*FlakeStatsResponse) Descriptor() ([]byte, []int) {
	return file_containerManager_proto_rawDescGZIP(), []int{12}
}

func (x *FlakeStatsResponse) GetFlakeStats() []*FlakeStats {
	if x != nil {
		return x.FlakeStats
	}
	return nil
}

type FlakeStatsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id []string `protobuf:"bytes,1,rep,name=id,proto3" json:"id,omitempty"`
}

func (x *FlakeStatsRequest) Reset() {
	*x = FlakeStatsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_containerManager_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FlakeStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlakeStatsRequest) ProtoMessage() {}

func (x *FlakeStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_containerManager_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlakeStatsRequest.ProtoReflect.Descriptor instead.
func (*FlakeStatsRequest) Descriptor() ([]byte, []int) {
	return file_containerManager_proto_rawDescGZIP(), []int{13}
}

func (x *FlakeStatsRequest) GetId() []string {
	if x != nil {
		return x.Id
	}
	return nil
}

type FlakeLogsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Logs []byte `protobuf:"bytes,1,opt,name=logs,proto3" json:"logs,omitempty"`
}

func (x *FlakeLogsResponse) Reset() {
	*x = FlakeLogsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_containerManager_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FlakeLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlakeLogsResponse) ProtoMessage() {}

func (x *FlakeLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_containerManager_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlakeLogsResponse.ProtoReflect.Descriptor instead.
func (*FlakeLogsResponse) Descriptor() ([]byte, []int) {
	return file_containerManager_proto_rawDescGZIP(), []int{14}
}

func (x *FlakeLogsResponse) GetLogs() []byte {
	if x != nil {
		return x.Logs
	}
	return nil
}

type FlakeLogsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tail string `protobuf:"bytes,1,opt,name=tail,proto3" json:"tail,omitempty"`
	Id   string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *FlakeLogsRequest) Reset() {
	*x = FlakeLogsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_containerManager_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FlakeLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlakeLogsRequest) ProtoMessage() {}

func (x *FlakeLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_containerManager_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlakeLogsRequest.ProtoReflect.Descriptor instead.
func (*FlakeLogsRequest) Descriptor() ([]byte, []int) {
	return file_containerManager_proto_rawDescGZIP(), []int{15}
}

func (x *FlakeLogsRequest) GetTail() string {
	if x != nil {
		return x.Tail
	}
	return ""
}

func (x *FlakeLogsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type FlakeMetaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FlakeMetaRequest) Reset() {
	*x = FlakeMetaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_containerManager_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FlakeMetaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlakeMetaRequest) ProtoMessage() {}

func (x *FlakeMetaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_containerManager_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlakeMetaRequest.ProtoReflect.Descriptor instead.
func (*FlakeMetaRequest) Descriptor() ([]byte, []int) {
	return file_containerManager_proto_rawDescGZIP(), []int{16}
}

var File_containerManager_proto protoreflect.FileDescriptor

var file_containerManager_proto_rawDesc = []byte{
	0x0a, 0x16, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x4d, 0x61, 0x6e, 0x61, 0x67,
	0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6b, 0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x74,
	0x61, 0x69, 0x6e, 0x65, 0x72, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x11, 0x0a, 0x04, 0x5f, 0x63, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x43, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07,
	0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x4e,
	0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x6f, 0x72, 0x63, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x66, 0x6f, 0x72, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x74,
	0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x74, 0x69,
	0x6d, 0x65, 0x6f, 0x75, 0x74, 0x22, 0x69, 0x0a, 0x0f, 0x6b, 0x6f, 0x6e, 0x67, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f,
	0x75, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x6f, 0x75, 0x74, 0x65,
	0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x50, 0x61, 0x74, 0x68, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x50, 0x61, 0x74, 0x68,
	0x22, 0x4e, 0x0a, 0x10, 0x6b, 0x6f, 0x6e, 0x67, 0x55, 0x70, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x4d, 0x65, 0x74, 0x61, 0x12, 0x22, 0x0a, 0x0c, 0x75, 0x70, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x75, 0x70, 0x73, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x61, 0x73, 0x68,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x68, 0x61, 0x73, 0x68, 0x6f, 0x6e,
	0x22, 0x85, 0x01, 0x0a, 0x08, 0x6b, 0x6f, 0x6e, 0x67, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x3a, 0x0a,
	0x0f, 0x6b, 0x6f, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4d, 0x65, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6b, 0x6f, 0x6e, 0x67, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x0f, 0x6b, 0x6f, 0x6e, 0x67, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x3d, 0x0a, 0x10, 0x6b, 0x6f, 0x6e,
	0x67, 0x55, 0x70, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x4d, 0x65, 0x74, 0x61, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6b, 0x6f, 0x6e, 0x67, 0x55, 0x70, 0x73, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x10, 0x6b, 0x6f, 0x6e, 0x67, 0x55, 0x70, 0x73, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x4d, 0x65, 0x74, 0x61, 0x22, 0xd6, 0x01, 0x0a, 0x0b, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x69, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x69, 0x12, 0x24,
	0x0a, 0x0d, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x50, 0x6f, 0x72, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72,
	0x50, 0x6f, 0x72, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x42, 0x61, 0x73, 0x65, 0x50, 0x6f, 0x72, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x42, 0x61, 0x73, 0x65, 0x50, 0x6f, 0x72, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x4d, 0x61, 0x78, 0x50, 0x6f, 0x72, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x4d, 0x61, 0x78, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x25, 0x0a, 0x08, 0x6b, 0x6f,
	0x6e, 0x67, 0x4d, 0x65, 0x74, 0x61, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x6b,
	0x6f, 0x6e, 0x67, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x08, 0x6b, 0x6f, 0x6e, 0x67, 0x4d, 0x65, 0x74,
	0x61, 0x22, 0x45, 0x0a, 0x13, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4d, 0x65, 0x74, 0x61,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x0b, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x22, 0x14, 0x0a, 0x12, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x3c,
	0x0a, 0x16, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x04, 0x6d, 0x65, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e,
	0x65, 0x72, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x22, 0x33, 0x0a, 0x17,
	0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x22, 0x93, 0x01, 0x0a, 0x09, 0x66, 0x6c, 0x61, 0x6b, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x20, 0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x68, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x22, 0x3d, 0x0a, 0x11, 0x66, 0x6c, 0x61, 0x6b, 0x65,
	0x4d, 0x65, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x09,
	0x66, 0x6c, 0x61, 0x6b, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0a, 0x2e, 0x66, 0x6c, 0x61, 0x6b, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x09, 0x66, 0x6c, 0x61,
	0x6b, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x22, 0x6a, 0x0a, 0x0a, 0x66, 0x6c, 0x61, 0x6b, 0x65, 0x53,
	0x74, 0x61, 0x74, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x65, 0x6d, 0x55, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x65, 0x6d, 0x55, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x63, 0x70, 0x75, 0x50, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x63, 0x70, 0x75, 0x50, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x4e, 0x65, 0x74, 0x77,
	0x6f, 0x72, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4e, 0x65, 0x74, 0x77, 0x6f,
	0x72, 0x6b, 0x22, 0x41, 0x0a, 0x12, 0x66, 0x6c, 0x61, 0x6b, 0x65, 0x53, 0x74, 0x61, 0x74, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x0a, 0x66, 0x6c, 0x61, 0x6b,
	0x65, 0x53, 0x74, 0x61, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x66,
	0x6c, 0x61, 0x6b, 0x65, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x0a, 0x66, 0x6c, 0x61, 0x6b, 0x65,
	0x53, 0x74, 0x61, 0x74, 0x73, 0x22, 0x23, 0x0a, 0x11, 0x66, 0x6c, 0x61, 0x6b, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x27, 0x0a, 0x11, 0x66, 0x6c,
	0x61, 0x6b, 0x65, 0x4c, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x6c, 0x6f, 0x67, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x6c,
	0x6f, 0x67, 0x73, 0x22, 0x36, 0x0a, 0x10, 0x66, 0x6c, 0x61, 0x6b, 0x65, 0x4c, 0x6f, 0x67, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x69, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x12, 0x0a, 0x10, 0x66,
	0x6c, 0x61, 0x6b, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x32,
	0xbf, 0x02, 0x0a, 0x10, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x4d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x72, 0x12, 0x44, 0x0a, 0x0f, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f,
	0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x12, 0x17, 0x2e, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x18, 0x2e, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x0b, 0x67, 0x65,
	0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x12, 0x13, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x11, 0x67, 0x65, 0x74, 0x41, 0x63, 0x74, 0x69, 0x76,
	0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x12, 0x11, 0x2e, 0x66, 0x6c, 0x61, 0x6b,
	0x65, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x66,
	0x6c, 0x61, 0x6b, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x38, 0x0a, 0x0d, 0x67, 0x65, 0x74, 0x46, 0x6c, 0x61, 0x6b, 0x65, 0x53, 0x74, 0x61, 0x74,
	0x73, 0x12, 0x12, 0x2e, 0x66, 0x6c, 0x61, 0x6b, 0x65, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x66, 0x6c, 0x61, 0x6b, 0x65, 0x53, 0x74, 0x61,
	0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x0c, 0x67, 0x65,
	0x74, 0x46, 0x6c, 0x61, 0x6b, 0x65, 0x4c, 0x6f, 0x67, 0x73, 0x12, 0x11, 0x2e, 0x66, 0x6c, 0x61,
	0x6b, 0x65, 0x4c, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e,
	0x66, 0x6c, 0x61, 0x6b, 0x65, 0x4c, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_containerManager_proto_rawDescOnce sync.Once
	file_containerManager_proto_rawDescData = file_containerManager_proto_rawDesc
)

func file_containerManager_proto_rawDescGZIP() []byte {
	file_containerManager_proto_rawDescOnce.Do(func() {
		file_containerManager_proto_rawDescData = protoimpl.X.CompressGZIP(file_containerManager_proto_rawDescData)
	})
	return file_containerManager_proto_rawDescData
}

var file_containerManager_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_containerManager_proto_goTypes = []interface{}{
	(*ContainerMeta)(nil),           // 0: containerMeta
	(*KongServiceMeta)(nil),         // 1: kongServiceMeta
	(*KongUpstreamMeta)(nil),        // 2: kongUpstreamMeta
	(*KongMeta)(nil),                // 3: kongMeta
	(*ServiceMeta)(nil),             // 4: serviceMeta
	(*ServiceMetaResponse)(nil),     // 5: serviceMetaResponse
	(*ServiceMetaRequest)(nil),      // 6: serviceMetaRequest
	(*DeleteContainerRequest)(nil),  // 7: deleteContainerRequest
	(*DeleteContainerResponse)(nil), // 8: deleteContainerResponse
	(*FlakeMeta)(nil),               // 9: flakeMeta
	(*FlakeMetaResponse)(nil),       // 10: flakeMetaResponse
	(*FlakeStats)(nil),              // 11: flakeStats
	(*FlakeStatsResponse)(nil),      // 12: flakeStatsResponse
	(*FlakeStatsRequest)(nil),       // 13: flakeStatsRequest
	(*FlakeLogsResponse)(nil),       // 14: flakeLogsResponse
	(*FlakeLogsRequest)(nil),        // 15: flakeLogsRequest
	(*FlakeMetaRequest)(nil),        // 16: flakeMetaRequest
}
var file_containerManager_proto_depIdxs = []int32{
	1,  // 0: kongMeta.kongServiceMeta:type_name -> kongServiceMeta
	2,  // 1: kongMeta.kongUpstreamMeta:type_name -> kongUpstreamMeta
	3,  // 2: serviceMeta.kongMeta:type_name -> kongMeta
	4,  // 3: serviceMetaResponse.serviceMeta:type_name -> serviceMeta
	0,  // 4: deleteContainerRequest.meta:type_name -> containerMeta
	9,  // 5: flakeMetaResponse.flakeMeta:type_name -> flakeMeta
	11, // 6: flakeStatsResponse.flakeStats:type_name -> flakeStats
	7,  // 7: containerManager.deleteContainer:input_type -> deleteContainerRequest
	6,  // 8: containerManager.getServices:input_type -> serviceMetaRequest
	16, // 9: containerManager.getActiveServices:input_type -> flakeMetaRequest
	13, // 10: containerManager.getFlakeStats:input_type -> flakeStatsRequest
	15, // 11: containerManager.getFlakeLogs:input_type -> flakeLogsRequest
	8,  // 12: containerManager.deleteContainer:output_type -> deleteContainerResponse
	5,  // 13: containerManager.getServices:output_type -> serviceMetaResponse
	10, // 14: containerManager.getActiveServices:output_type -> flakeMetaResponse
	12, // 15: containerManager.getFlakeStats:output_type -> flakeStatsResponse
	14, // 16: containerManager.getFlakeLogs:output_type -> flakeLogsResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_containerManager_proto_init() }
func file_containerManager_proto_init() {
	if File_containerManager_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_containerManager_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContainerMeta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_containerManager_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KongServiceMeta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_containerManager_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KongUpstreamMeta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_containerManager_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KongMeta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_containerManager_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceMeta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_containerManager_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceMetaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_containerManager_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceMetaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_containerManager_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteContainerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_containerManager_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteContainerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_containerManager_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FlakeMeta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_containerManager_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FlakeMetaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_containerManager_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FlakeStats); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_containerManager_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FlakeStatsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_containerManager_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FlakeStatsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_containerManager_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FlakeLogsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_containerManager_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FlakeLogsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_containerManager_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FlakeMetaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_containerManager_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_containerManager_proto_goTypes,
		DependencyIndexes: file_containerManager_proto_depIdxs,
		MessageInfos:      file_containerManager_proto_msgTypes,
	}.Build()
	File_containerManager_proto = out.File
	file_containerManager_proto_rawDesc = nil
	file_containerManager_proto_goTypes = nil
	file_containerManager_proto_depIdxs = nil
}
